APP_TITLE = 'BlueStacks App Player'
MAIN_MENU = '../resources/mainmenu/'
MM_HOME = '../resources/mainmenu/home.png'
MM_VILLAGE = '../resources/mainmenu/village.png'
MM_DRAKENBERG = '../resources/mainmenu/drakenberg.png'

MM_DRAKENBERG_TRADINGPOST = '../resources/mainmenu/village/drakenberg/enter_trading_post.png'
TRADINGPOST_GOLD1 = '../resources/mainmenu/village/drakenberg/trading_post/gold.png'
TRADINGPOST_GOLD2 = '../resources/mainmenu/village/drakenberg/trading_post/gold_available.png'
TRADINGPOST_BACK = '../resources/mainmenu/village/drakenberg/trading_post/back.png'

DRAKENBERG_ROAMING = '../resources/mainmenu/village/drakenberg/roaming.png'
ROAMING_GO = '../resources/mainmenu/village/drakenberg/roaming/go.png'
ROAMING_OK = '../resources/mainmenu/village/drakenberg/roaming/ok.png'
ROAMING_CANCEL = '../resources/mainmenu/village/drakenberg/roaming/cancel.png'
ROAMING_BACK = '../resources/mainmenu/village/drakenberg/roaming/back.png'

SCHOOL_EDUCATE = '../resources/mainmenu/village/school/educate.png'
SCHOOL_BELOW_PUPILS = '../resources/mainmenu/village/school/below_pupils.png'
SCHOOL_BACK = '../resources/mainmenu/village/school/back.png'

VILLAGE_SCHOOL = '../resources/mainmenu/village/school.png'
VILLAGE_KITCHEN = '../resources/mainmenu/village/enter_kitchen.png'
KITCHEN_SERVE = '../resources/mainmenu/village/kitchen/serve.png'
KITCHEN_OK = '../resources/mainmenu/village/kitchen/ok.png'
KITCHEN_ORDER_JEWELS = '../resources/mainmenu/village/kitchen/order_jewels.png'
KITCHEN_CANCEL = '../resources/mainmenu/village/kitchen/cancel.png'
KITCHEN_GUESTS_AVAILABLE = '../resources/mainmenu/village/kitchen/guests_available.png'

DRAKENBERG_GUILD = '../resources/mainmenu/village/drakenberg/enter_guild.png'
GUILD_CANCEL = '../resources/mainmenu/village/drakenberg/guild/cancel.png'
GUILD_HANDLE = '../resources/mainmenu/village/drakenberg/guild/handle.png'
GUILD_REQUESTS = '../resources/mainmenu/village/drakenberg/guild/random_requests.png'

DRAKENBERG_STAGE = '../resources/mainmenu/village/drakenberg/stage.png'
STAGE_CHALLENGE = '../resources/mainmenu/village/drakenberg/stage/challenge.png'
CHALLENGE_EMPTY = '../resources/mainmenu/village/drakenberg/stage/challenge/items_empty.png'
CHALLENGE_GOLD = '../resources/mainmenu/village/drakenberg/stage/challenge/gold_motivation.png'
CHALLENGE_ITEM = '../resources/mainmenu/village/drakenberg/stage/challenge/item_motivation.png'
CHALLENGE_NEGOTIATE = '../resources/mainmenu/village/drakenberg/stage/challenge/negotiate.png'
CHALLENGE_CONTINUE = '../resources/mainmenu/village/drakenberg/stage/challenge/tap_to_continue.png'

STAGE_GO = '../resources/mainmenu/village/drakenberg/stage/go.png'
EVENTS_CONTINUE = '../resources/mainmenu/village/drakenberg/stage/events/tap_to_continue.png'
STAGE_EVENTS_X = '../resources/mainmenu/village/drakenberg/stage/events_x.png'
STAGE_EVENTS_Y = '../resources/mainmenu/village/drakenberg/stage/events_y.png'
STAGE_AUTOHANDLE = '../resources/mainmenu/village/drakenberg/stage/events/autohandle.png'
